In [1]:
import h5py
import numpy as np
import pandas as pd

# Cálculo

In [2]:
with h5py.File('Table_TNG300_snapshot99_wSpins_wEnv_ALL.hdf5', 'r') as f:
    # Leer los subgrupos necesarios
    haloSubGr = np.array(f['SubGroups']['SubhaloGrNr']) 
    SubhaloMassType = f['SubGroups']['SubhaloMassType'][:]
    SubhaloStellarPhotometrics_g = f['SubGroups']['SubhaloStellarPhotometrics_g'][:]
    SubhaloStellarPhotometrics_i = f['SubGroups']['SubhaloStellarPhotometrics_i'][:]
    SubhaloSFR = f['SubGroups']['SubhaloSFR'][:]
    #SubhaloHalfmassRad = f['SubGroups']['SubhaloHalfmassRad'][:]
    SubhaloHalfmassRadType = f['SubGroups']['SubhaloHalfmassRadType'][:]
    

In [3]:
SubhaloMassType.shape

(3033931, 6)

In [4]:
SubhaloMassType[:1]

array([[1.9187548e+14, 1.0860912e+15, 0.0000000e+00, 0.0000000e+00,
        5.3094845e+12, 6.9895447e+10]], dtype=float32)

In [5]:
stellar_mass = SubhaloMassType[:, 4]

In [6]:
stellar_mass.shape

(3033931,)

In [7]:
color_g_i = SubhaloStellarPhotometrics_g - SubhaloStellarPhotometrics_i

sSFR = SubhaloSFR / SubhaloMassType[:, 4]
sSFR[sSFR == 0] = 10**-13.5

galaxy_size = SubhaloHalfmassRadType[:,4]

C:\Users\bjnic\AppData\Local\Temp\ipykernel_3144\2215814510.py:3: RuntimeWarning: divide by zero encountered in divide
  sSFR = SubhaloSFR / SubhaloMassType[:, 4]
C:\Users\bjnic\AppData\Local\Temp\ipykernel_3144\2215814510.py:3: RuntimeWarning: invalid value encountered in divide
  sSFR = SubhaloSFR / SubhaloMassType[:, 4]


In [8]:
X = np.column_stack((haloSubGr, stellar_mass, color_g_i, galaxy_size, sSFR))

In [9]:
stellar_mass_threshold = 10**8.75

stellar_masses = X[:, 1]

mask = stellar_masses >= stellar_mass_threshold

X = X[mask]

In [10]:
X.shape

(305066, 5)

In [11]:
X[111346:111349]

array([[9.90600000e+03, 6.15775642e+10, 1.12636185e+00, 5.49060392e+00,
        3.16227757e-14],
       [9.90600000e+03, 9.37944064e+09, 8.86205673e-01, 4.28508377e+00,
        3.60682907e-11],
       [9.90600000e+03, 1.48718784e+09, 9.76839066e-01, 6.37313700e+00,
        3.16227757e-14]])

In [12]:
np.log10(X[111346:111349])

array([[ 3.99589832e+00,  1.07894225e+01,  5.16779313e-02,
         7.39620116e-01, -1.35000000e+01],
       [ 3.99589832e+00,  9.97217694e+00, -5.24654741e-02,
         6.31959317e-01, -1.04428744e+01],
       [ 3.99589832e+00,  9.17236583e+00, -1.01769805e-02,
         8.04353254e-01, -1.35000000e+01]])

In [13]:
X.shape

(305066, 5)

In [14]:
unique_groups, indices = np.unique(X[:, 0], return_index=True)
X = X[indices]

In [15]:
X.shape

(174785, 5)

In [16]:
df = pd.DataFrame(X, columns=['SubhaloGrNr', 'stellar_mass', 'color_g_i', 'galaxy_size', 'sSFR'])

In [17]:
df['stellar_mass'] = df['stellar_mass'].apply(np.log10)
df['galaxy_size'] = df['galaxy_size'].apply(np.log10)
df['sSFR'] = df['sSFR'].apply(np.log10)

In [18]:
df[9906:9907]

SubhaloGrNr  stellar_mass  color_g_i  galaxy_size  sSFR
9906       9906.0     10.789423   1.126362      0.73962 -13.5

In [19]:
df[58423:58424]

SubhaloGrNr  stellar_mass  color_g_i  galaxy_size      sSFR
58423      58430.0      9.915116   0.596603     0.648354 -9.830829

In [20]:
df[29920:29921]

SubhaloGrNr  stellar_mass  color_g_i  galaxy_size       sSFR
29920      29920.0     10.343463    0.97584     0.597454 -11.411541

In [21]:
df.shape

(174785, 5)

In [22]:
df = df.dropna()

In [23]:
df.shape

(174785, 5)

In [24]:
df = df.drop_duplicates()

In [25]:
df.shape

(174785, 5)

In [26]:
df.to_csv('galaxias.csv')